name: 'Module-VM-Package'
 
on:
  # push:
  #   branches:
  #   - main
  # pull_request:
  workflow_dispatch:
 
jobs:
  terraform:
    name: 'Init, Plan and Package'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest    
 
    defaults:
      run:
        shell: bash
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:        
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: "./terraform"
         
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
 
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./terraform"

    - uses: actions/upload-artifact@v3
      with:
        name: terraform-module-azure-vm-1.0.0.${{ github.run_number }}
        path: ./*.tf