name: 'Terraform - Destroy'
 
on:
  workflow_dispatch:
 
jobs:
  terraform:
    name: 'Terraform-Destroy'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production
 
    defaults:
      run:
        shell: bash
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
 
    - name: Terraform Destroy
      if: github.ref == 'refs/heads/main'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'destroy'
        tf_actions_working_dir: "./terraform"
