name: 'StarApp-Release'
 
on:
  # push:
  #   branches:
  #   - main
  # pull_request:
  workflow_dispatch:
 
jobs:
  job-release-package:
    name: 'Package Architecture'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: build
 
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v2
    
    - name: Download multiple workflow artifacts  
      uses: marcofaggian/action-download-multiple-artifacts@v3.0.7
      with:        
        workflow: terraform-module-azure-vm-package.yml        
        names: terraform-module-azure-vm-1.0.0.1
        paths: ./modules/vm  
        
    - name: Display structure of downloaded files
      run: tree
      working-directory: ./

    - uses: actions/upload-artifact@v3
      with:
        name: terraform-azure-starapp-1.0.0.${{ github.run_number }}
        path: ./modules/vm


  job-release-dev:
    needs: job-release-package
    name: 'Release DEV'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: dev
 
    defaults:
      run:
        shell: bash
 
    steps:

    - uses: actions/download-artifact@v3
      with:       
        path: ./

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
         
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./terraform"  

    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main'
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 1.2.7
    #     tf_actions_subcommand: 'apply'
    #     tf_actions_working_dir: "./terraform"

  job-destroy-dev:
    needs: job-release-dev
    name: 'Release DEV'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: dev
 
    defaults:
      run:
        shell: bash
 
    steps:

    - uses: actions/download-artifact@v3
      with:       
        path: ./

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.7
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
         
    # - name: 'Terraform Destroy'
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 1.2.7
    #     tf_actions_subcommand: 'destroy'
    #     tf_actions_working_dir: "./terraform"  